# -*- coding: utf-8 -*-
"""Zad1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0h3Ix0Nsm-pTf019y_Bce_xVk78CI0V
"""

import numpy as np

tabzero = np.zeros(10,np.int64)
print("Tablica z 10 zerami",tabzero)
tabfive = np.full(10,5)
print("Tablica z 10 piatkamii",tabfive)
tab10to50 = np.arange(10,51,1) 
print("Tablica z liczbami od 10 do 50",tab10to50)
tabmatrix = np.arange(0,9,1)
tabmatrix = tabmatrix.reshape(3,3)
print("Macierz 3x3 z liczbami od 0 do 8",tabmatrix)
matrix1 = np.eye(3,3,dtype=np.int64)
print("Macierz jednostkowa 3x3",matrix1)
matrixgauss = np.random.normal(size=(5,5))
print("Macierz Gaussa 5x5",matrixgauss)
tab001 = np.arange(0.01,1.01,0.01)
tab001 = tab001.reshape(10,10)
print("Macierz 10x10 od 0.01 do 1",tab001)
tablins = np.linspace(0,1,20)
print("Tablica liniowa od 0 do 1",tablins)
tabrandom = random.randint(26, size=(25))
tabrandom = tabrandom.reshape(5,5)
print("Macierz 5x5 z losowymi liczbami z przedzialu 0-25",tabrandom)
print("Suma macierzy 5x5",tabrandom.sum())
print("Srednia macierzy 5x5",tabrandom.mean())
print("Standardowa dewiacja macierzy 5x5",np.std(tabrandom))
tabsumcolumns = np.sum(tabrandom,axis=0)
print("Suma kolumn macierzy 5x5",tabsumcolumns)
matrix100 = np.random.randint(0,101,(5,5))
print("Macierzy 5x5 z liczbami zprzedzialu 0-100",matrix100)
print("Mediana macierzy 5x5",np.median(matrix100))
print("Minimalna wartosc macierzy 5x5",np.min(matrix100))
print("Maksymalna wartosc macierzy 5x5",np.max(matrix100))
matrixtrans = np.random.randint(0,100,(3,5))
print("Macierz przed transspose",matrixtrans)
matrixtrans =  np.transpose(matrixtrans)
print("Macierz po transpose",matrixtrans)
matrixadd1 = np.random.randint(0,10,(3,3))
matrixadd2 = np.random.randint(0,10,(3,3))
print("Wynik dodaniu dwoch macierzy 3x3",np.add(matrixadd1,matrixadd2))
matrixmultiply1 = np.random.randint(0,10,(4,3))
matrixmultiply2 = np.random.randint(0,10,(3,4))
print("Wynik mnozenia macierzy 4x3 i 3x4 z uzyciem matmul",np.matmul(matrixmultiply1,matrixmultiply2))
print("Wynik mnozenia macierzy 4x3 i 3x4 z uzyciem dot",matrixmultiply1.dot(matrixmultiply2))