# -*- coding: utf-8 -*-
"""Zad4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fw10AcgA0oME2sUrwKP81_98W68ToYnv
"""

from openpyxl import Workbook
from google.colab import drive
import requests
from bs4 import BeautifulSoup
from random import choices
from string import ascii_lowercase
drive.mount('/content/gdrive', force_remount=True)
test_filename = 'Lawecki_175IC.xlsx'
wb = Workbook()
wb.create_sheet("Linki")
wb.create_sheet("Filmweb")
ws = wb.active
ws.title="Gielda"
ws["A1"] = "Skrot"
ws["B1"] = "Kurs"
ws["C1"] = "Zmiana kursu"
ws["D1"] = "Transakcja"

i = 0
exchange_list = []
save_exchange_list = []
while i < 2:
  random_letter = "".join(choices(ascii_lowercase, k=3))
  p = {"s": random_letter}
  odpowiedz = requests.get("http://stooq.pl/q/", params=p)
  soup = BeautifulSoup(odpowiedz.text, 'html.parser')
  znacznik_kurs = soup.find("span", id=f"aq_{random_letter}_c2")
  if znacznik_kurs!=None:
    exchange_list.append(random_letter)
    i += 1
# kurs
# podejście 1: po id
for spolka in exchange_list:
  p = {"s": spolka}
  odpowiedz = requests.get("http://stooq.pl/q/", params=p)
  soup = BeautifulSoup(odpowiedz.text, 'html.parser')
  znacznik_kurs = soup.find("span", id=f"aq_{spolka}_c2")
  kurs = float(znacznik_kurs.text)
#zmiana kursu
  znacznik_zmiana_bezwzgledna = soup.find("span", id=f"aq_{spolka}_m2")
  znacznik_zmiana_wzgledna = soup.find("span", id=f"aq_{spolka}_m3")
  zmiana_bezwzgledna = float(znacznik_zmiana_bezwzgledna.text)
  zmiana_wzgledna = float(znacznik_zmiana_wzgledna.text[1:-2])/100
# transakcje
  znacznik_transakcje =  soup.find("span", id=f"aq_{spolka}_n1")
  transakcje = float(znacznik_transakcje.text)
  save_exchange_list.append([kurs,zmiana_bezwzgledna,transakcje])

for i in range(2):
  ws[f"A{i+2}"] = exchange_list[i]
  ws[f"B{i+2}"] = save_exchange_list[i][0]
  ws[f"C{i+2}"] = save_exchange_list[i][1]
  ws[f"D{i+2}"] = save_exchange_list[i][2]



ws2 = wb["Linki"]
ws2["A1"] = "Link"
odpowiedz = requests.get("https://www.filmweb.pl/film/Jojo+Rabbit-2019-817417")
soup = BeautifulSoup(odpowiedz.text, 'html.parser')
j=2
for link in soup.find_all('a', href=True):
    ws2[f"A{j}"] = link.get('href')
    j = j +1

ws3 = wb["Filmweb"]
ws3["A1"] = "Tytul filmu"
ws3["B1"] = "Rezyser"
ws3["C1"] = "Data premiery"
ws3["D1"] = "Boxoffice"
ws3["E1"] = "Ocena"
wb.save('/content/gdrive/My Drive/'+test_filename)
odpowiedz = requests.get("https://www.filmweb.pl/film/Jojo+Rabbit-2019-817417")
soup = BeautifulSoup(odpowiedz.text, 'html.parser')
ocena = float(soup.find("span", itemprop="ratingValue").text.replace(",", "."))
rezyseria = soup.find("span", itemprop="name").text
oryginalny_tytul = soup.find("span", itemprop="url").text
premiera = soup.find(string="premiera:").next_element.find("a").text
boxoffice = int(soup.find(text="boxoffice:").next_element.text[1:].replace(" ", ""))
ws3["A2"] = oryginalny_tytul
ws3["B2"] = rezyseria
ws3["C2"] = premiera
ws3["D2"] = boxoffice
ws3["E2"] = ocena
wb.save('/content/gdrive/My Drive/'+test_filename)