# -*- coding: utf-8 -*-
"""Zad2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBfgFMUVQijLAyfHxqAou4l26a8gDt1Y
"""

import pandas

googleSheetId = '1nmQQSTMN3aYB44vt3cNsrbWp3Idn-gVGQzPI48f1CcQ'
worksheetName = 'samochody1tys'
URL = 'https://docs.google.com/spreadsheets/d/{0}/gviz/tq?tqx=out:csv&sheet={1}'.format(
	googleSheetId,
	worksheetName
)

df = pandas.read_csv(URL)
#1 Srednia cena samochodow
print(df['cena'].mean())
#2 Mediana przebiegu
print(df['przebieg'].median())
#3 Unikatowe marki
print(df['marka'].drop_duplicates())
#4 Wykres prezentujaca ilosc samochodow w danej cenie
df['cena'].plot.hist()
#5 Wykres prezentujaca stosunek przebiegu do ceny samochodu
df.plot.scatter(x='przebieg',y='cena')
#6 Wyswietleneie trzech losowych wierszy
print(df.sample(n=3))
#7 Wyswietlenei listy ssamochodow po cenie
print(df.sort_values('cena'))
#8 Wyswietlenie liczby samochodow nalezacych do danej marki
print(df['marka'].value_counts())
#9 wyswietenie listy tylko z kolumnami 1, 2 i 5
print(df.iloc[:,[1,2,5]])
#10 wyswietlenie marki wojowodztwa i ceny samochodw tanszych niz 1000
print(df.loc[df['cena'] < 1000, ['marka','wojewodztwo','cena']])